arch: amd64
os: linux
dist: focal
language: cpp
env:
  - VCPKG_TRIPLET=x64-linux

addons:
  apt:
    update: true
    packages:
      - ccache
      - build-essential
      - cmake
      - libluajit-5.1-dev
      - tar
      - curl
      - zip
      - unzip
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: $SONAR_TOKEN

compiler:
  - gcc

install:
  - |
    cd /home/travis/build/opentibiabr
    git clone https://github.com/microsoft/vcpkg
    ./vcpkg/bootstrap-vcpkg.sh
    ./vcpkg/vcpkg integrate install

script:
  - cd /home/travis/build/opentibiabr/otservbr-global
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=/home/travis/build/opentibiabr/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - make -j`nproc`
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.ccache/'
     - '/home/travis/build/opentibiabr/vcpkg/installed'
